tread/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from treadweb import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tread/', include('treadweb.urls')),
    path('', views.home_page, name='home'),
]

treadweb/urls.py
from django.urls import path
from django.urls import re_path
from . import views

app_name = 'treadweb'
urlpatterns = [
    re_path(r'^$', views.home_page, name='home'),
    re_path(r'^search/$', views.search_page, name='search'),
    path('search/<str:keyword>', views.search_keyword, name='search_keyword'),
    path('channel/', views.channel_page, name='channel'),
    path('video/', views.video_page, name='video'),
    path('video/<str:tag>', views.video_tag, name='video_tag'),
]

treadweb/models.py
from django.db import models

# Create your models here.
class Keyword(models.Model):
    age = models.CharField(max_length=50)
    content = models.CharField(max_length=50)

treadweb/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_protect
from treadweb.collector.naverDataLab import NaverDataLab
from treadweb.collector.wordcloud import TreadWordCloud
from treadweb.collector.googleTrend import GoogleTrend
from datetime import datetime
from treadweb.collector.youtube_api_channelInfo import ChannelInfo
from treadweb.collector.youtube_api_search import YoutubeSearch
from multiprocessing import Process
import os

import json
# Create your views here.
def home_page(request):
    return render(request, 'treadweb/base_home.html')

@cache_page(10)
@csrf_protect
def search_page(request):
    naver = NaverDataLab()
    now = datetime.now()
    time = now.strftime("%Y-%m-%dT%H:%M:%S")
    keyword_rank = naver.naver_searchlist(time)
    return render(request, 'treadweb/base_search.html', {"keyword_rank": keyword_rank})

@cache_page(10)
@csrf_protect
def search_keyword(request, keyword):
    naver = NaverDataLab()
    wc = TreadWordCloud()
    pr1 = Process(target=wc.draw_cloud, args=(keyword,))
    pr1.start()
    line_result = naver.load_data(keyword)
    keywords = list()
    keywords.append(keyword)
    googletrend = GoogleTrend(keyword=keywords)
    googletrend.set_payload()
    region_result = googletrend.load_data('region')
    donut_result = googletrend.load_data('gender')
    pr1.join()
    WC_exists = 'yes' if os.path.exists('treadweb/static/treadweb/img/wordcloud.png') else 'no'
    return JsonResponse({
        'line_result': line_result,
        'region_result': region_result,
        'gender_result': donut_result,
        'WC_exists': WC_exists
    }, json_dumps_params={'ensure_ascii': True})

def channel_page(request):
    youtube = YoutubeSearch()
    channels = youtube.search_channel_orderby_view();
    channel_list = []
    channel_info = ChannelInfo()
    for channel in channels:
        channel_data = channel_info.get_channel_data(channel["channel_id"])
        channel_list.append(channel_data)

    return render(request, 'treadweb/base_channel.html',
                  {
                      'channel_list': channel_list
                    }
                  )

def video_page(request):
    youtube = YoutubeSearch()
    tag_keys = list(youtube.tags.keys())
    n = len(tag_keys) // 2
    tag_list = [tag_keys[:n], tag_keys[n + 1:]]
    video_list = youtube.search_video_by_category(0)
    return render(request, 'treadweb/base_video.html',
                  {
                      'tag_list': tag_list,
                      'video_list': video_list
                    }
                  )


def video_tag(request, tag):
    youtube = YoutubeSearch()
    tag_keys = list(youtube.tags.keys())
    n = len(tag_keys) // 2
    tag_list = [tag_keys[:n], tag_keys[n + 1:]]
    tag_id = youtube.tags.get(tag)
    video_list = youtube.search_video_by_category(tag_id)
    return render(request, 'treadweb/base_video.html',
                  {
                      'tag_list': tag_list,
                      'video_list': video_list
                  }
                  )

treadweb/templates/treadweb/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width", initial-scale="1">
<meta http-equiv='cache-control' content='no-cache'>
<meta http-equiv='expires' content='0'>
<meta http-equiv='pragma' content='no-cache'>

  <!-- Libraries CSS Files -->
  <link href="//maxcdn.bootstrap.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

<title>트리드 - 트렌드를 읽다</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
    {% load staticfiles %}
    <!-- JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.2/dist/vue.js"></script>
    <script src="https://unpkg.com/vue-router@3.0.1/dist/vue-router.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.js"></script>
    <script src="https://d3js.org/d3.v3.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>


    <!-- CSS -->
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900|Quicksand:400,700|Questrial" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.18/c3.min.css">
    <link href="{% static 'treadweb/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'treadweb/css/default.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>

<div id="header-wrapper">
  <div id="header">
    <div id="logo">
      <a class="navbar-brand" href="{% url 'treadweb:home' %}">TREAD</a>
    </div>
    <div id="menu">
      <ul>
                {% block menu %}
                {% endblock menu %}
      </ul>
    </div>
  </div>
</div>

<div id="page-wrapper">
    {% block body0 %}
    {% endblock body0 %}

    {% block body1 %}
    {% endblock body1%}

    {% block body2 %}
    {% endblock body2 %}

    {% block body3 %}
    {% endblock body3 %}
</div>

<div id="copyright">
  <div class="container">
  <p>&copy; All rights reserved. | Design by TREAD.</p>
  </div>
</div>

    <script src="{% static 'treadweb/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'treadweb/js/chart_vue.js' %}"></script>
    <script src="{% static 'treadweb/js/rank_vue.js' %}"></script>

</body>
</html>

treadweb/templates/treadweb/base_channel.html
{% extends "base.html" %}

{% block menu %}
    <li><a href="{% url 'treadweb:home' %}" accesskey="1" title="">Home</a></li>
    <li><a href="{% url 'treadweb:search' %}" accesskey="2" title="">Search</a></li>
    <li class="current_page_item"><a href="{% url 'treadweb:channel' %}" accesskey="3" title="">Channel</a></li>
    <li><a href="{% url 'treadweb:video' %}" accesskey="4" title="">Video</a></li>
    <li><a data-toggle="modal" data-target="#myModal" href="#myModal"><i class="fa fa-envelope-o"></i></a></li>
{% endblock menu %}

{% block body0 %}

{% endblock body0 %}

{% block body1 %}
    <div class="youtube-table-wrapper">
        <div class="youtube-table-header">
            <div class="header-item rank">순위</div>
            <div class="header-item">유튜버</div>
            <div class="header-item value">구독자 수</div>
            <div class="header-item value">조회 수</div>
            <div class="header-item value">영상 수</div>
        </div>
        {% if channel_list %}
            {% for channel in channel_list %}
        <div class="youtube-table-body">
            <div class="body-item rank"><span>{{ forloop.counter }}</span></div>
            <div class="body-item left">
                <span><img src="{{ channel.thumbnails }}"/></span>
                <span>{{ channel.title }}</span></div>
            <div class="body-item value"><span>{{ channel.subscriber }}</span></div>
            <div class="body-item value"><span>{{ channel.view_count }}</span></div>
            <div class="body-item value"><span>{{ channel.video_count }}</span></div>
        </div>
            {% endfor %}
       {% endif %}
    </div>
{% endblock body1 %}

{% block body2 %}
{% endblock body2 %}

treadweb/templates/treadweb/base_home.html
{% extends "base.html" %}

{% block menu %}
    <li class="current_page_item"><a href="{% url 'treadweb:home' %}" accesskey="1" title="">Home</a></li>
    <li><a href="{% url 'treadweb:search' %}" accesskey="2" title="">Search</a></li>
    <li><a href="{% url 'treadweb:channel' %}" accesskey="3" title="">Channel</a></li>
    <li><a href="{% url 'treadweb:video' %}" accesskey="4" title="">Video</a></li>
    <li><a data-toggle="modal" data-target="#myModal" href="#myModal"><i class="fa fa-envelope-o"></i></a></li>
{% endblock menu %}

{% block body0 %}
    <div id="main-wrapper">
        <div class="row centered">
          <div id="home-content" class="col-lg-8 col-lg-offset-2">
            <h1>Read Trend information <b>in 2019</b></h1>
            <h2>You get the latest trends from us <br>give you more information about the trend keyword</h2>
          </div>
        </div>
    </div>
{% endblock body0 %}

{% block body1 %}
<div class="container w">
  <div class="row centered">
    <br><br>
    <div class="col-lg-4">
      <i class="fa fa-google"></i>
      <h4>GOOGLE TREND</h4>
      <p>There are many variations of passages</p>
  </div>

  <div class="col-lg-4">
    <i class="fa fa-database"></i>
    <h4>NAVER</h4>
    <p>There are many variation of passages</p>
  </div>

  <div class="col-lg-4">
    <i class="fa fa-youtube"></i>
    <h4>YOUTUBE</h4>
    <p>There are many variation of passages</p>
  </div>
</div>
<br><br>
</div>

{% endblock body1 %}

{% block body2 %}
{% endblock body2 %}

treadweb/templates/treadweb/base_search.html
{% extends "base.html" %}
{% load staticfiles %}
{% block menu %}
    <li><a href="{% url 'treadweb:home' %}" accesskey="1" title="">Home</a></li>
    <li class="current_page_item"><a href="{% url 'treadweb:search' %}" accesskey="2" title="">Search</a></li>
    <li><a href="{% url 'treadweb:channel' %}" accesskey="3" title="">Channel</a></li>
    <li><a href="{% url 'treadweb:video' %}" accesskey="4" title="">Video</a></li>
    <li><a data-toggle="modal" data-target="#myModal" href="#myModal"><i class="fa fa-envelope-o"></i></a></li>
{% endblock menu %}

{% block body0 %}
    <div class="wrap">
       <div class="search">
          <input type="text" id="keyword_text" class="searchTerm" placeholder="검색어를 입력하세요.">
          <button class="searchButton" onclick="search_keyword()">
            <i class="fa fa-search"></i>
         </button>
       </div>
    </div>
    <div class="container">
        <div class="keyword_rank">
            {% for age, rank_list in keyword_rank.items %}
            <div class="rank_inner">
                <strong class="rank_title">{{ age }}</strong>
                <ul class="rank_list">
                    {% for word in rank_list %}
                    <li class="list">
                        <div class="list_area" onclick="search_keyword('{{ word }}')">
                            <span class="num">{{ forloop.counter }}</span>
                            <span class="list_title">{{ word }}</span>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock body0 %}

{% block body1 %}
    <line-chart-component></line-chart-component>
{% endblock body1 %}

{% block body2 %}
    <div class="container">
        <region-chart-component></region-chart-component>
        <gender-chart-component></gender-chart-component>
	</div>
    <wordcloud-component></wordcloud-component>

{% endblock body2 %}

treadweb/templates/treadweb/base_video.html
{% extends "base.html" %}

{% block menu %}
    <li><a href="{% url 'treadweb:home' %}" accesskey="1" title="">Home</a></li>
    <li><a href="{% url 'treadweb:search' %}" accesskey="2" title="">Search</a></li>
    <li><a href="{% url 'treadweb:channel' %}" accesskey="3" title="">Channel</a></li>
    <li class="current_page_item"><a href="{% url 'treadweb:video' %}" accesskey="4" title="">Video</a></li>
    <li><a data-toggle="modal" data-target="#myModal" href="#myModal"><i class="fa fa-envelope-o"></i></a></li>
{% endblock menu %}

{% block body0 %}
    <div class="tagd">
    {% if tag_list %}
        {% for tags in tag_list %}
        <div class="tagd-wrapper">
            <div class="tagd-items">
                {% for tag in tags %}
                    <div class="tagd-item"><a href="{% url 'treadweb:video_tag' tag %}">#{{ tag }}</a></div>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    {% endif %}
    </div>
{% endblock body0 %}

{% block body1 %}
    <div class="youtube-table-wrapper">
        <div class="youtube-table-header">
            <div class="header-item">인기 영상</div>
        </div>
        {% if video_list %}
        <div class="contents">
        {% for video in video_list %}
            <div class="item-section" id="video{{ forloop.counter }}">
                <div class="video-renderer" onclick="setVideo({{ forloop.counter }}, '{{ video.video_id }}')">
                    <div class="video-item rank"><span>{{ forloop.counter }}</span></div>
                    <div class="video-item video-thumbnails" >
                        <span>
                            <img src="{{ video.video_thumbnail }}"/>
                        </span>
                    </div>
                    <div class="video-item video-text-wrapper">
                        <div class="title-wrapper" onclick="setVideo({{ forloop.counter }}, '{{ video.video_id }}')">
                            <p>{{ video.video_title }}</p>
                        </div>
                        <div class="byline-separated">
                            <p>{{ video.channel_title }} • 조회수 {{ video.view_count }} • {{ video.publishedAt }}</p>
                        </div>
                    </div>
                </div>
                <div class="video-wrapper" v-if="isSet">
                     <div class="video">
                        <video-component></video-component>
                    </div>
                    <div class="video-description">
                        <template v-if="isSet">
                            <p>{{ video.description }}</p>
                        </template>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
        {% endif %}
    </div>
{% endblock body1 %}

{% block body2 %}

{% endblock body2 %}